name: ProceduralDungeon
version: 1.0.0
description: Generate some dungeon with random rooms
authors: [Zarinoow]
main: fr.foxelia.proceduraldungeon.Main
depend: [WorldEdit]
commands:
  dungeon:
    description: Dungeon command.